### PR TITLE
Fix #25 : goToDate() don't scroll to specific date

### LINKED ISSUE #25: goToDate() don't scroll to specific date
weekView.setDateTimeInterpreter(new DateTimeInterpreter() {
            @Override
            public String interpretDate(Calendar date) {
                SimpleDateFormat weekdayNameFormat = new SimpleDateFormat("EEE", Locale.getDefault());
                String weekday = weekdayNameFormat.format(date.getTime());
                SimpleDateFormat format = new SimpleDateFormat(" d/MMM", Locale.getDefault());

                return weekday.toUpperCase() + format.format(date.getTime());
            }

            @Override
            public String interpretTime(int hour) {
                if (hour == 24) hour = 0;
                if (hour == 0) hour = 0;
                return hour + ":00";
            }
        });

        Calendar calendar = Calendar.getInstance();
        calendar.setTimeInMillis(dateSelected);

        weekView.goToDate(calendar);

What is wrong? It is not scrolling do dateSelected, can you help me?

### PR DESCRIPTION
**Pull request by Bwaim**
This PR contains :

- A correction to fix #25
- Improve the computation of the difference for the first display in week view for any first day
- The goToDate() in week view correctly display the first day wanted
- Change in the Basic Example (with static WeekView) to test the goToDate() function

### CODE REVIEW

**Comment by Bwaim** [comment]
I commited a new version taking into account the remarks.
I added a correction to compute the last day visible correctly.

**Comment by thellmund** [comment]
In the activity with the static example, navigation via the buttons doesn’t work correctly yet, though it seems like this issue wasn’t caused by any of your commits. I’ll approve this pull request and take a look at that issue separately.

**Comment by Bwaim** [comment]
What do you mean by not working well ? If you talk about the refresh of the date in the header, maybe we can increase the delay in the `refreshText()` method. Actually the first visible day and last visible day are refreshed at draw time. Maybe we should update them in the `goToDate()` function too ?

**Comment by thellmund** [comment]
Sorry, I should have been more explicit: When setting a particular date via `goToDate()`, tapping the right-arrow button does not perform any action. Also, tapping the left-arrow button results in going back two weeks instead of one.

**Comment by thellmund** [comment]
That’s odd: The problem does not occur when I set the date to January 10th, but it does occur when I set some date in August 🤔

**Comment by Bwaim** [comment]
The problem is in line 1017 in `goToDate()` function
`DateUtils.getDaysUntilDate(date)`
There is a limitation in `val dateInMillis = date.withTimeAtStartOfDay().timeInMillis`, surely a capacity problem.

**Pull request merged**
